### ISSUE TITLE
Images are not loading properly

### ISSUE THREAD

**Issue by nelsondurairaj** [GatoGamer1155/gatogamer1155.github.io#3]
![image](https://user-images.githubusercontent.com/78611909/210790659-c0369c69-a21b-44d4-8e84-7f77f9bbdc7c.png)

it is simple issue not impact anyone

**Comment by GatoGamer1155** [comment]
Cagaste, Omar se metió hasta la cocina, ahora estamos full pwned, te recomendaria que revisaras tu ordenador, seguro tienes un spyware ofuscado con persistencia y todo, en todo caso habla con Chema Alonso para que te ayude a recuperar tus datos, y a Alvaro Chirou para que te aplique un Cross Site Scripting, de paso con Antonio Sarosi para que te enseñe Laravel, vale?
